# Deplyment aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: temp
  template:
    metadata:
      labels:
        app: temp
    spec:
      containers:
      - name: temp
        image: acthiago/temperatura:latest
        ports:
          - containerPort: 8080
---
# servico aplicação
apiVersion: v1
kind: Service
metadata:
  name: temp
spec:
  selector:
    app: temp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer